# This file was generated by GoReleaser. DO NOT EDIT.
cask "incorpus" do
  version "0.1.6"

  on_macos do
    on_intel do
      sha256 "11ec1fbfd687eadb4dfe810d4b069f2abc492d3b4f45ee0df680dfec97f347fc"
      url "https://github.com/srank-com-my/incorpus-cli/releases/download/v#{version}/incorpus_#{version}_macOS_x86_64.tar.gz"
    end
    on_arm do
      sha256 "f0fa73db714aa61f3adf4ea3cf3a6f1fefb84014f20fbd72a847519c478b0973"
      url "https://github.com/srank-com-my/incorpus-cli/releases/download/v#{version}/incorpus_#{version}_macOS_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ec531892b8eb6819e42da85472c0bd029aab97816a3545c1e635ecbed4b7d06f"
      url "https://github.com/srank-com-my/incorpus-cli/releases/download/v#{version}/incorpus_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "17ec2f89126e30eec8a65ca29db5a832cdece1539fd36bed861beb6fafd80125"
      url "https://github.com/srank-com-my/incorpus-cli/releases/download/v#{version}/incorpus_#{version}_linux_arm64.tar.gz"
    end
  end

  name "incorpus"
  desc "Agentic CLI for the Incorpus business management platform"
  homepage "https://incorpus.app"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "incorpus"

  # No zap stanza required

end
