# This file was generated by GoReleaser. DO NOT EDIT.
cask "incorpus" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "9f5df427d1d5f71d3a15a7bd1bd0edf5c73acd90b07caca3e045c6489782b808"
      url "https://github.com/srank-com-my/incorpus-cli/releases/download/v#{version}/incorpus_#{version}_macOS_x86_64.tar.gz"
    end
    on_arm do
      sha256 "c2c03ec33cae389740db51d29d2a00ade1c3734a21a829ce79fe3236fab47a03"
      url "https://github.com/srank-com-my/incorpus-cli/releases/download/v#{version}/incorpus_#{version}_macOS_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "48ebc9e281ed9c4522aa0d2aa15f706fbac1e658e156ce344754930c40147620"
      url "https://github.com/srank-com-my/incorpus-cli/releases/download/v#{version}/incorpus_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "0b9c7c90c578be2e5523ee9d4fd1586f986f8c05fa7feabb627eb21c2d181f63"
      url "https://github.com/srank-com-my/incorpus-cli/releases/download/v#{version}/incorpus_#{version}_linux_arm64.tar.gz"
    end
  end

  name "incorpus"
  desc "Agentic CLI for the Incorpus business management platform"
  homepage "https://incorpus.app"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "incorpus"

  # No zap stanza required

end
