# This file was generated by GoReleaser. DO NOT EDIT.
cask "incorpus" do
  version "0.16.1"

  on_macos do
    on_intel do
      sha256 "426122847d56936c779f3a598e51162175b41a26298782378f1d3a05639e5997"
      url "https://github.com/srank-com-my/incorpus-cli/releases/download/v#{version}/incorpus_#{version}_macOS_x86_64.tar.gz"
    end
    on_arm do
      sha256 "e8f9772430b984caf05f852b0679717572ce2f67db1695f8cc79169f9da9344c"
      url "https://github.com/srank-com-my/incorpus-cli/releases/download/v#{version}/incorpus_#{version}_macOS_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a1c0ab527be0ee89917993b4afb993a5779a97175ad230149cccd6eb816fcce2"
      url "https://github.com/srank-com-my/incorpus-cli/releases/download/v#{version}/incorpus_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "ca6e8f735677ba8056091b25c9f9955def375a31a915c692479de28036d3635c"
      url "https://github.com/srank-com-my/incorpus-cli/releases/download/v#{version}/incorpus_#{version}_linux_arm64.tar.gz"
    end
  end

  name "incorpus"
  desc "Agentic CLI for the Incorpus business management platform"
  homepage "https://incorpus.app"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "incorpus"

  # No zap stanza required

end
